### ISSUE TITLE
make build-kong error

### ISSUE THREAD

**Issue by segry** [Kong/kong-build-tools#187]
hi, I need your help
params:
RESTY_IMAGE_BASE?=centos
RESTY_IMAGE_TAG?=7
PACKAGE_TYPE?=rpm

error message:
Step 24/25 : RUN /tmp/build-openresty.sh
 ---> Running in fa4a798ef98e
/bin/sh: /tmp/build-openresty.sh: /bin/bash^M: bad interpreter: No such file or directory
The command '/bin/sh -c /tmp/build-openresty.sh' returned a non-zero code: 126
make[1]: *** [build-openresty] Error 126
make[1]: Leaving directory `/home/code/kong-build-tools'
make: *** [actual-build-kong] Error 2

**Comment by hutchic** [comment]
What's the host system you're running on? At a glance it looks like `build-openresty.sh` needs to be ran through dos2unix
