### ISSUE TITLE
Error while building openresty using openresty-build-tools/kong-ngx-build script

### ISSUE THREAD

**Issue by charitha306** [Kong/kong-build-tools#261]
I get the following error when I run the `./kong-ngx-build -p buildroot --openresty 1.13.6.2 --openssl 1.1.1b --luarocks 3.0.4 --pcre 8.43` command

In file included from <base_dir>/kong-build-tools/openresty-build-tools/work/lua-kong-nginx-module/stream/src/ngx_stream_lua_kong_module.c:21:
../ngx_stream_lua-0.0.5/src/api/ngx_stream_lua_api.h:49:1: error: unknown type name 'ngx_stream_lua_request_t'; did you mean 'ngx_stream_lua_value_t'?
ngx_stream_lua_request_t *ngx_stream_lua_get_request(lua_State *L);
^~~~~~~~~~~~~~~~~~~~~~~~
ngx_stream_lua_value_t
../ngx_stream_lua-0.0.5/src/api/ngx_stream_lua_api.h:44:3: note: 'ngx_stream_lua_value_t' declared here
} ngx_stream_lua_value_t;
  ^
<base_dir>/kong-build-tools/openresty-build-tools/work/lua-kong-nginx-module/stream/src/ngx_stream_lua_kong_module.c:57:43: error: unknown type name 'ngx_stream_lua_request_t'; did you mean
      'ngx_stream_lua_value_t'?
ngx_stream_lua_kong_ffi_proxy_ssl_disable(ngx_stream_lua_request_t *r)
                                          ^~~~~~~~~~~~~~~~~~~~~~~~
                                          ngx_stream_lua_value_t
../ngx_stream_lua-0.0.5/src/api/ngx_stream_lua_api.h:44:3: note: 'ngx_stream_lua_value_t' declared here
} ngx_stream_lua_value_t;
  ^
<base_dir>/kong-build-tools/openresty-build-tools/work/lua-kong-nginx-module/stream/src/ngx_stream_lua_kong_module.c:61:11: warning: implicit declaration of function 'ngx_stream_lua_get_module_ctx' is
      invalid in C99 [-Wimplicit-function-declaration]
    ctx = ngx_stream_lua_get_module_ctx(r, ngx_stream_lua_kong_module);
          ^
<base_dir>/kong-build-tools/openresty-build-tools/work/lua-kong-nginx-module/stream/src/ngx_stream_lua_kong_module.c:61:9: warning: incompatible integer to pointer conversion assigning to
      'ngx_stream_lua_kong_ctx_t *' from 'int' [-Wint-conversion]
    ctx = ngx_stream_lua_get_module_ctx(r, ngx_stream_lua_kong_module);
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<base_dir>/kong-build-tools/openresty-build-tools/work/lua-kong-nginx-module/stream/src/ngx_stream_lua_kong_module.c:63:30: error: no member named 'pool' in 'ngx_stream_lua_value_t'
        ctx = ngx_pcalloc(r->pool, sizeof(ngx_stream_lua_kong_ctx_t));
                          ~  ^
<base_dir>/kong-build-tools/openresty-build-tools/work/lua-kong-nginx-module/stream/src/ngx_stream_lua_kong_module.c:68:9: warning: implicit declaration of function 'ngx_stream_lua_set_ctx' is invalid in
      C99 [-Wimplicit-function-declaration]
        ngx_stream_lua_set_ctx(r, ctx, ngx_stream_lua_kong_module);
        ^
3 warnings and 3 errors generated.
  CC       libpcre_la-pcre_globals.lo
make[2]: *** [objs/addon/src/ngx_stream_lua_kong_module.o] Error 1

**Comment by hutchic** [comment]
Making the following change to pin an external dependency fixed this for me

```
diff --git a/openresty-build-tools/kong-ngx-build b/openresty-build-tools/kong-ngx-build
index 0aaba18..3a09d1f 100755
--- a/openresty-build-tools/kong-ngx-build
+++ b/openresty-build-tools/kong-ngx-build
@@ -11,7 +11,7 @@ LUAROCKS_VER=
 PCRE_VER=
 FORCE=0
 OPENRESTY_PATCHES=$OPENRESTY_PATCHES
-KONG_NGINX_MODULE=master
+KONG_NGINX_MODULE=9d9308f3a179b611b11a913291d25e8bb3c19544
 DEBUG=0
 NPROC=
 OS=
```

Tell me if this resolves the issue for you as well. These look like the prerequisites to build Kong 0.15?

**Comment by dndx** [comment]
Your OpenResty version is too old, use 1.15.8.2 instead.
