### ISSUE TITLE
How to build kong 1.3.0

### ISSUE THREAD

**Issue by chuan-T** [Kong/kong-build-tools#368]
I'm trying to compile kong version 1.3.0 and running make test-kong with the latest version of the compiler fails.
I want to know which kong-build-tools version should be used.

below is error info:
Step 10/42 : RUN curl -fsSLo /tmp/yaml-${LIBYAML_VERSION}.tar.gz https://pyyaml.org/download/libyaml/yaml-${LIBYAML_VERSION}.tar.gz     && cd /tmp     && tar xzf yaml-${LIBYAML_VERSION}.tar.gz     && ln -s /tmp/yaml-${LIBYAML_VERSION} /tmp/yaml     && cd /tmp/yaml     && ./configure       --libdir=/tmp/build/usr/local/kong/lib       --includedir=/tmp/yaml-${LIBYAML_VERSION}     && make install     && ./configure --libdir=/usr/local/kong/lib     && make install     && rm -rf /tmp/yaml-${LIBYAML_VERSION}
 ---> Running in 318b77320c41
curl: (22) The requested URL returned error: 404
The command '/bin/sh -c curl -fsSLo /tmp/yaml-${LIBYAML_VERSION}.tar.gz https://pyyaml.org/download/libyaml/yaml-${LIBYAML_VERSION}.tar.gz     && cd /tmp     && tar xzf yaml-${LIBYAML_VERSION}.tar.gz     && ln -s /tmp/yaml-${LIBYAML_VERSION} /tmp/yaml     && cd /tmp/yaml     && ./configure       --libdir=/tmp/build/usr/local/kong/lib       --includedir=/tmp/yaml-${LIBYAML_VERSION}     && make install     && ./configure --libdir=/usr/local/kong/lib     && make install     && rm -rf /tmp/yaml-${LIBYAML_VERSION}' returned a non-zero code: 22
make[1]: *** [build-openresty] Error 22
make: *** [kong-test-container] Error 2

Is it due to the version of the tool, if so, which version should I use to compile the 1.3.0 version of kong?
Thanks

**Comment by hutchic** [comment]
That's a quite old version of Kong. I'd encourage you to upgrade :)

Try kong-build-tools at the 1.0.3 tag
