### ISSUE TITLE
kong-build-tools should minimize external curls

### ISSUE THREAD

**Issue by kikito** [Kong/kong-build-tools#458]
I am in the process of releasing older versions of the gateway (2.1 up to 2.8) and I have hit two problems, which are related with how we download dependencies.

Problem 1: Dependency on external servers

Openresty depends on the PCRE. We [use curl](https://github.com/Kong/kong-build-tools/blob/master/openresty-build-tools/kong-ngx-build#L314) to download it and compile it. The PCRE maintainers choose to change its download location. We "fixed" that problem by changing the path in our script (#418) ... which is fine until someone like me needs to release an older kong(like 2.4) again. That kong will point to an older kong-build-tools that doesn't include #418. I can bump kong-build-tools in the 2.4 branch in order to get that change, but then I will also get changes that might not be compatible with kong 2.4. So then I might need a custom build of kbt, just for 2.4, including #418.

Even if the PRCE guys don't change anything, their server can simply go down. When that happens we will not be able to build Kong. And the same will happen with all of our dependencies.

Problem 2: Dependency on the network

The fact that our servers need to "reach out" to the outside world is a problem on itself. A single network glitch will delay a kong release by ~1 hour. Debian jessie built-in SSL certificates have all expired, so it cannot build (which is probably fine, it would likely fail to build because of other reasons anyway since it is EOL. The point is that ideally it should not need to reach out and use SSL just to build kong).

----

While #418 solved the issue for that particular moment and that particular kong release, the underlying problems remain.

A crude alternative would have been downloading a bunch of zipfiles for all the PCRE versions that kong-build-tools supports and put them inside this repo. And the same with other dependencies (OpenSSL etc)

I am sure there are more refined ways to handle this, with some sort of file-cache, at least for our [jenkins builds](https://www.jenkins.io/doc/pipeline/steps/jobcacher/). Some sort of "try the cache first, and if it doesn't work, download from the internet (and maybe put it on the cache afterwards)".

**Comment by flrgh** [comment]
Seems like we would get a lot of mileage out of a source code mirror tool/service that we control. It should be smarter than a simple caching http proxy so that it can present a simple rest API. So, `GET /PCRE/10.39` would fetch the asset from $upstream, validate the checksum/signature, and stash it in S3 for next time (with some kind of medium-ish lifecycle policy) before returning it to the caller. The next layer would use this mirror in conjunction with the asset cache mechanism of $build_system (jenkins, github actions) for short-term storage.

:thinking: google is failing me at the moment, but I feel like a tool like this _has_ to exist already, because this is such a common problem. In the past I've used [aptly](https://www.aptly.info/) to fulfill a similar role, but that was much more use-case specific since it's aimed at being a .deb package mirror.

**Comment by kikito** [comment]
I got some feedback through a different venue on this:

> Recent versions of kbt scoped the docker cache key a little better so this problem effects us less but isn't yet entirely resolved. The KBT cache key for the lowest / slowest layer is now `${BUILD_TOOLS_SHA}-${REQUIREMENTS_SHA}${OPENRESTY_PATCHES}`

This means that Docker does the caching (we already depend on it for other things, so this brings no extra dependencies). Once it downloads once, it will keep the downloads in the cache. It doesn't fully solve the problem because we still depend on the network the first time. It can also "mask" problems (kong will get built even if PCRE changes locations on their servers, until you bump the kbt sha). It is better than a more specific file-caching tool int hat it can be used easily other places besides our Jenkins server.

The other piece of information I didn't know is that kong-build-tools is supposed to be "backwards-compatible". In theory we should be able to build older versions of Kong with recent versions of kbt. This suggest a different approach to what I was trying - start with the most recent version of kbt and "go backwards" if things go wrong, instead of starting with the oldest one and trying to patch it.

**Comment by fffonion** [comment]
Caching those source codes somewhere like in a github repo (then update it using Actions), and fallback to the orignal url seems a good idea. It also helps mitigating with supply chain attacks.

**Comment by fffonion** [comment]
We will have fallback URLs and checksum support by Bazel, so closing this now please reopen if needed : )
