### ISSUE TITLE
This operation will bring great surprise

### ISSUE THREAD

**Issue by Murphy-hub** [Kong/kong-build-tools#555]
## operation
```
$ ./openresty-build-tools/kong-ngx-build -p /usr/local --openresty 1.19.9.1 --openssl 1.1.1 -f
```
## consequence
Your `/usr/local` directory will be cleared

## proposal
It is recommended to add directory detection to prevent directory deletion by mistake, which has a great impact and is very angry

**Comment by fffonion** [comment]
Closing because of the sunset of this repository, we now fix this in bazel build : )
