### ISSUE TITLE
Building Kong from source fail because of wrong submodules versions

### ISSUE THREAD

**Issue by Elyahou** [Kong/kong-build-tools#645]
When building kong from source in version `3.1.0`, the`kong-build-tools/openresty-build-tools/kong-ngx-build` command fail with this error:

```
error: unknown type name 'mdb_size_t'
```

`kong-ngx-build` run with `--resty-lmdb 1.0.0` as requested for this version of Kong, but the issue is that `kong-ngx-build` do not checkout correct version of submodule `lmdb` in the [lua-resty-lmdb](https://github.com/Kong/lua-resty-lmdb) repository. 

I opened a PR to fix this issue: https://github.com/Kong/kong-build-tools/pull/644

**Comment by hanshuebner** [comment]
We are no longer maintaining this repository as Kong is now build by Bazel: https://github.com/Kong/kong/tree/master/build
